name: Deploy

on:
  push:
    branches:
      - amandaleeanne-Schock-finalSubmission
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem

          cat >> ~/.ssh/config <<EOF
          Host my-vps
              HostName $SSH_IP
              User $SSH_USER
              IdentityFile ~/.ssh/deploy-key.pem
              StrictHostKeyChecking no
          EOF
      - name: Test SSH
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_IP: ${{ secrets.SSH_IP }}
        run: |
            ssh -vvv \
            -i ~/.ssh/deploy-key.pem \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            "$SSH_USER@$SSH_IP" \
            "echo connected"
      - name: Verify key
        run: |
            ls -la ~/.ssh
            file ~/.ssh/deploy-key.pem
            ssh-keygen -lf ~/.ssh/deploy-key.pem
      - name: Print project root directory
        run: |
          ssh my-vps 'cd "${{ secrets.PROJECT_ROOT }}" && pwd'